apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-virtualservice
  namespace: digg-arbetsprov-prod
spec:
  hosts:
    - "*"
  gateways:
    - app-gateway
  http:
    
    - match:
        - uri:
            prefix: "/api/v2"  
      route:
        - destination:
            host: new-version-service  
            port:
              number: 8080

   
    - match:
        - uri:
            prefix: "/api"  
      route:
        - destination:
            host: new-app-service  
            port:
              number: 8080

    
    - route:
        - destination:
            host: arbeidsprov-app  
            port:
              number: 8080
